name = "penniless-json-repair"
main = "src/entry.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "penniless-data-utilities-counters"
database_id = "e699ef23-03c6-4d78-8c5c-e49c93813cd9"

[vars]
X402_NETWORK = "eip155:8453"
X402_FACILITATOR = "https://facilitator.payai.network"
X402_PRICE = "$0.001"
X402_PAY_TO = "0x3D98800c64C345950E1eAaa076D88C12d1BF5F37"
